FROM composer:1.7.2 as dependencies
WORKDIR /app

COPY composer.json composer.lock ./
COPY . .
# Ignoring platform requirements because if not disabled, composer checks for php
# extension packages in the system which will be installed in the final stage
RUN composer validate \
    && composer install \
        --no-scripts --optimize-autoloader \
        --ignore-platform-reqs --no-interaction --no-progress --ansi 

FROM equipo01-backend-php:latest

RUN apt-get update -y \
      && apt-get install -y --no-install-recommends git zip unzip libzip-dev libsqlite3-dev \
      && docker-php-source extract \
      && docker-php-ext-install zip pdo_sqlite \
      && docker-php-ext-enable zip pdo_sqlite \
      && docker-php-source delete

WORKDIR /app
# Dependency files
COPY --from=dependencies /app/vendor/ vendor/
COPY --from=dependencies /app/composer.json /app/composer.lock ./

RUN touch database/database.sqlite \
      && php artisan optimize:clear

# Re-do runtime configuration
ENV DATABASE_URL= WAIT_HOSTS=
ENV APP_ENV=local APP_DEBUG=true APP_KEY=base64:Q0hBTkdFX01FX1BMRUFTRQ== DB_CONNECTION=sqlite

# Erase previous entrypoint
ENTRYPOINT [""]
# Run tests
CMD /app/vendor/bin/phpunit --log-junit reports/tests.xml --coverage-html reports/html/ --stop-on-fail && chmod -R 777 reports/
