apiVersion: v1
kind: ConfigMap
metadata:
  name: ejemplo-php-config
  labels:
    app: ejemplo-php
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_KEY: "base64:Q0hBTkdFX01FX1BMRUFTRQ=="
  DATABASE_URL: "mysql://root:secret@database:3306/backend_laravel"
  WAIT_HOSTS: "database:3306"
