apiVersion: v1
kind: Secret
metadata:
  name: ejemplo-php-secret
  labels:
    app: ejemplo-php
type: Opaque
data:
  APP_KEY: "Q0hBTkdFTUVQTEVBU0U="
  DATABASE_URL: "bXlzcWw6Ly9yb290OkNIQU5HRU1FUExFQVNFQGRhdGFiYXNlOjMzMDYvYmFja2VuZF9sYXJhdmVs"
