apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../k8s
  - ../../base

namePrefix: dev-

namespace: ejemplo-php

patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment
      name: ejemplo-php
  - path: resource-limits.yaml
    target:
      kind: Deployment
      name: ejemplo-php

configMapGenerator:
  - name: ejemplo-php-env
    behavior: create
    literals:
      - ENVIRONMENT=dev
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_LEVEL=debug

generatorOptions:
  disableNameSuffixHash: true
